version: '2.14.0'

services:
  social-media:
    image: 'shafreen/social-media:0.0.1'
    ports:
      - '9090:9090'
    depends_on: 
      - jaeger
      - sentiment-analysis
      - mysql-setup
      - sts
    network_mode: "host"

  sms-sender:
    image: 'shafreen/sms-sender-service:0.0.1'
    depends_on: 
      - jaeger
      - nats
      - mysql-setup
    network_mode: "host"

  sentiment-analysis:
    image: 'shafreen/sentiment-api:0.0.1'
    ports:
      - '9099:9099'
    depends_on: 
      - jaeger
    network_mode: "host"

  jaeger:
    image: 'jaegertracing/opentelemetry-all-in-one'
    ports:
      - '13133:13133'
      - '16686:16686'
      - '55680:55680'
    network_mode: "host"

  sts:
    image: 'shafreen/sts-service:0.0.1'
    ports:
      - '9445:9445'
    network_mode: "host"

  mysql-setup:
    image: 'shafreen/db-setup:0.0.1'
    network_mode: "host"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    network_mode: "host"
